spring:
  application:
    name: store-job
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:5432/${POSTGRES_DB}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:Post123321}
    driver-class-name: org.postgresql.Driver
  flyway:
    baseline-on-migrate: true
    schemas: job
  jpa:
    properties:
      hibernate:
        default_schema: job

management:
  endpoints:
    web:
      base-path: /jobs/actuator
      exposure:
        include: [ 'prometheus' ]

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
 
springdoc:
  api-docs:
    path: /jobs/v3/api-docs
  swagger-ui:
    path: /jobs/swagger-ui.html